### ISSUE TITLE
Several Ontologies of TIB fail in ingestion

### ISSUE THREAD

**Issue by giraygi** [TIBHannover/ols4#11]
**Describe the bug**
Detailed list of exceptions can be found here: [exceptions.txt](https://github.com/TIBHannover/ols4/files/15130006/exceptions.txt).

**To Reproduce**
Config file that infludes all failing ontologies: [failing_ontologies.json](https://github.com/TIBHannover/ols4/files/15130161/failing_ontologies.json). Prefixes of ontologies are: abcd,battinfo,bau,bdsubj,cco,cgo,cora,coy,dfgfo,ecso,fabio,fiestaiot,gpo,gta,icitygeom,mdv,openadr,ore,osmo,raum,scor,sepio,sustaingraph,sweet,t4fs,tiva,dolce,dpbo,extruont,peco,hoom,snomedct,bk

**Expected behavior**
Those ontologies need to be indexed as they do in ols3

**Comment by deepananbu** [comment]
Also refer: https://github.com/EBISPOT/ols4/issues/453
