### ISSUE TITLE
Search filter based on collection returns nothing

### ISSUE THREAD

**Issue by Pooya-Oladazimi** [TIBHannover/ols4#72]
**Describe the bug**
search filter based on a collection returns nothing although the result exists.

**To Reproduce**
call: /api/search?q=assay&start=0&groupField=iri&rows=20&schema=collection&classification=NFDI4CHEM

equivalent in ols3: https://service.tib.eu/ts4tib/api/search?q=assay&start=0&groupField=iri&rows=20&schema=collection&classification=NFDI4CHEM

**Additional context**
Besides the empty result issue, facet data looks funny:
![Screenshot from 2024-10-17 13-38-05](https://github.com/user-attachments/assets/ea57e7c6-4a56-4c18-ab6b-b13fd5026345)

**Comment by giraygi** [comment]
The call in the description work in prod1 but not in prod2
When I change the call as api/search?q=assay&schemas=collection&classifications=NFDI4CHEM it returns results both in prod1 and prod2. I will investigate why the variable names needs to change.

**Comment by giraygi** [comment]
It has been observed that only the first shot of ingestion is filtered by the call.

**Comment by giraygi** [comment]
It has been observed that the filtered records retrieved are for the first page that has a size of 10.
