### ISSUE TITLE
ontology_prefix is sometimes missing from the select result 

### ISSUE THREAD

**Issue by Pooya-Oladazimi** [TIBHannover/ols4#73]
**Describe the bug**
ontology_prefix is sometimes missing from the select result. Sometimes is there and sometimes not.

**To Reproduce**
missing: /api/select?q=assa&rows=20&ontology=&type=class,property

not missing example: /api/select?q=assay&rows=20&ontology=&type=class,property

**Comment by giraygi** [comment]
The reason is ncit config file doesn't include preferredPrefix
