### ISSUE TITLE
chebi ontology showing incorrect values for classes and properties

### ISSUE THREAD

**Issue by deepananbu** [TIBHannover/ols4#90]
While browsing ontologies in terminology service for chebi ontology. Classes and properties are shown as zero,

url: https://terminology.tib.eu/ts/ontologies?and=false&sortedBy=title&page=1&size=10&keyword=chebi

![image](https://github.com/user-attachments/assets/16832e23-d919-4c67-9001-d8b6c4c43654)

![image](https://github.com/user-attachments/assets/fd4569bc-94ea-42ab-b99f-eac617e41d42)

**Comment by giraygi** [comment]
This repo is not related to this issue.
